const recipes = [
  {
    id: "1",
    title: "Simple Oatmeal Pancakes",
    category: "Breakfast",
    image: "/assets/images/item-1.jpeg",
    amount: "8 pancakes",
    prepTime: "5 min",
    cookTime: "20 min",
    totalTime: "25 min",
    ingredient1: "2 cups old-fashioned rolled oats (GF if desired)",
    ingredient2: "1 cup (250 mL) unsweetened plant-based milk",
    ingredient3: "1/3 cup (100 g) apple sauce*",
    ingredient4: "2 Tbsp (30 mL) maple syrup",
    ingredient5: "1 Tbsp (15 mL) coconut oil, melted",
    ingredient6: "1 tsp (4 g) baking powder",
    ingredient7: "2 tsp (8 g) ground cinnamon",
    ingredient8: "1 tsp (5 mL) pure vanilla extract",
    ingredient9: "1/2 tsp salt",
    ingredient10: "1 Tbsp (15 mL) coconut or vegetable oil, if needed",
    directions1: "In a food processor, blend the oatmeal into a flour.",
    directions2: "Combine all the ingredients in a bowl.",
    directions3:
      "Preheat a large frying pan on medium-high heat. If your pan isn't non-stick, add a small bit of oil, and when hot, spoon about 1/4 cup of batter onto the pan and let cook. Flip when the top of the pancakes are bubbly and the sides look firm, about 2-3 minutes. Cook the other side for another 2-3 minutes.",
    directions4: "Top with desired toppings and enjoy.",
  },
  {
    id: "2",
    title: "Simple Oatmeal Pancakes",
    category: "Dinner",
    image: "/assets/images/item-2.jpeg",
    amount: "8 pancakes",
    prepTime: "5 min",
    cookTime: "20 min",
    totalTime: "25 min",
    ingredient1: "2 cups old-fashioned rolled oats (GF if desired)",
    ingredient2: "1 cup (250 mL) unsweetened plant-based milk",
    ingredient3: "1/3 cup (100 g) apple sauce*",
    ingredient4: "2 Tbsp (30 mL) maple syrup",
    ingredient5: "1 Tbsp (15 mL) coconut oil, melted",
    ingredient6: "1 tsp (4 g) baking powder",
    ingredient7: "2 tsp (8 g) ground cinnamon",
    ingredient8: "1 tsp (5 mL) pure vanilla extract",
    ingredient9: "1/2 tsp salt",
    ingredient10: "1 Tbsp (15 mL) coconut or vegetable oil, if needed",
    directions1: "In a food processor, blend the oatmeal into a flour.",
    directions2: "Combine all the ingredients in a bowl.",
    directions3:
      "Preheat a large frying pan on medium-high heat. If your pan isn't non-stick, add a small bit of oil, and when hot, spoon about 1/4 cup of batter onto the pan and let cook. Flip when the top of the pancakes are bubbly and the sides look firm, about 2-3 minutes. Cook the other side for another 2-3 minutes.",
    directions4: "Top with desired toppings and enjoy.",
  },
  {
    id: "3",
    title: "Simple Oatmeal Pancakes",
    category: "Lunch",
    image: "/assets/images/item-5.jpeg",
    amount: "8 pancakes",
    prepTime: "5 min",
    cookTime: "20 min",
    totalTime: "25 min",
    ingredient1: "2 cups old-fashioned rolled oats (GF if desired)",
    ingredient2: "1 cup (250 mL) unsweetened plant-based milk",
    ingredient3: "1/3 cup (100 g) apple sauce*",
    ingredient4: "2 Tbsp (30 mL) maple syrup",
    ingredient5: "1 Tbsp (15 mL) coconut oil, melted",
    ingredient6: "1 tsp (4 g) baking powder",
    ingredient7: "2 tsp (8 g) ground cinnamon",
    ingredient8: "1 tsp (5 mL) pure vanilla extract",
    ingredient9: "1/2 tsp salt",
    ingredient10: "1 Tbsp (15 mL) coconut or vegetable oil, if needed",
    directions1: "In a food processor, blend the oatmeal into a flour.",
    directions2: "Combine all the ingredients in a bowl.",
    directions3:
      "Preheat a large frying pan on medium-high heat. If your pan isn't non-stick, add a small bit of oil, and when hot, spoon about 1/4 cup of batter onto the pan and let cook. Flip when the top of the pancakes are bubbly and the sides look firm, about 2-3 minutes. Cook the other side for another 2-3 minutes.",
    directions4: "Top with desired toppings and enjoy.",
  },
  {
    id: "4",
    title: "Simple lunch Pancakes",
    category: "Lunch",
    image: "/assets/images/item-4.jpeg",
    amount: "8 pancakes",
    prepTime: "5 min",
    cookTime: "20 min",
    totalTime: "25 min",
    ingredient1: "2 cups old-fashioned rolled oats (GF if desired)",
    ingredient2: "1 cup (250 mL) unsweetened plant-based milk",
    ingredient3: "1/3 cup (100 g) apple sauce*",
    ingredient4: "2 Tbsp (30 mL) maple syrup",
    ingredient5: "1 Tbsp (15 mL) coconut oil, melted",
    ingredient6: "1 tsp (4 g) baking powder",
    ingredient7: "2 tsp (8 g) ground cinnamon",
    ingredient8: "1 tsp (5 mL) pure vanilla extract",
    ingredient9: "1/2 tsp salt",
    ingredient10: "1 Tbsp (15 mL) coconut or vegetable oil, if needed",
    directions1: "In a food processor, blend the oatmeal into a flour.",
    directions2: "Combine all the ingredients in a bowl.",
    directions3:
      "Preheat a large frying pan on medium-high heat. If your pan isn't non-stick, add a small bit of oil, and when hot, spoon about 1/4 cup of batter onto the pan and let cook. Flip when the top of the pancakes are bubbly and the sides look firm, about 2-3 minutes. Cook the other side for another 2-3 minutes.",
    directions4: "Top with desired toppings and enjoy.",
  },
];
export default recipes;
